name: ifac2020
channels:
  - conda-forge
dependencies:
  - python=3.7
  - scikit-learn
  - scipy
  - matplotlib
  - numpy<1.17
  - anaconda::tensorflow=1.14
  - pytorch::pytorch=1.2
  - cudatoolkit=10.0
  - jupyter
  - pandas
  - tqdm
  - pylint
  - pip
  - pip:
    - https://git.isis.vanderbilt.edu/ahmedi/pystatespace/-/archive/v0.1.0/pystatespace-v0.1.0.tar.gz
    - gym
    - gast==0.2.2
    - stable-baselines[mpi]==2.9
