name: rl
channels:
  - conda-forge
dependencies:
  - python=3.7
  - scikit-learn
  - tslearn
  - scipy
  - matplotlib>=3.3.2
  - numpy
  - pytorch::pytorch=1.5
  - optuna
  - cudatoolkit=10.2
  - pandas
  - tqdm
  - swig
  - protobuf
  # Developement tools
  - jupyter
  - pylint
  - jupyter_contrib_nbextensions
  - pip
  - pip:
    - gym[box2d]
    - stable-baselines3>=0.9.0
    - tensorboard
    - tensorboardX
    - joblib
    - higher>=0.2.1
