name: rl
channels:
  - conda-forge
dependencies:
  - python=3.7
  - scikit-learn
  - scipy
  - matplotlib>=3.3.2
  - numpy
  - pytorch::pytorch=1.5
  - cudatoolkit=10.2
  - pandas
  - tqdm
  - swig
  # Developement tools
  - jupyter
  - pylint
  - jupyter_nbextensions_configurator
  - pip
  - pip:
    - gym[box2d]
    - stable-baselines3==0.9.0
    - tensorboard
    - joblib
    - higher==0.2.1
