name: rl
channels:
  - conda-forge
dependencies:
  - python=3.7
  - scikit-learn
  - scipy
  - matplotlib
  - numpy<1.17
  - anaconda::tensorflow-gpu=1.14
  - pytorch::pytorch=1.2
  - cudatoolkit=10.0
  - pandas
  - tqdm
  - swig
  # Developement tools
  - jupyter
  - pylint
  - jupyter_nbextensions_configurator
  - pip
  - pip:
    - gym[box2d]
    - gast==0.2.2
    - stable-baselines[mpi]==2.10
    - tensorboardx==2.0
    - joblib==0.14.1
