name: rl
channels:
  - conda-forge
dependencies:
  - python=3.7
  - scikit-learn
  - scipy
  - matplotlib
  - numpy<1.17
  - anaconda::tensorflow=1.14
  - pytorch::cpuonly
  - pytorch::pytorch=1.2
  - pandas
  - tqdm
  - swig
  # Developement tools
  - jupyter
  - pylint
  - pip
  - pip:
    - https://git.isis.vanderbilt.edu/ahmedi/pyTorchBridge/-/archive/master/pyTorchBridge-master.tar.gz
    - https://git.isis.vanderbilt.edu/ahmedi/pyStateSpace/-/archive/master/pyStateSpace-master.tar.gz
    - gym[box2d]
    - gast==0.2.2
    - stable-baselines[mpi]==2.10
    - tensorboardx==2.0
